service: authorizer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc

package:
  individually: true

functions:
  hello:
    handler: handlers/hello.handler
    package:
      patterns:
        - "!handlers/**"
        - "handlers/hello.js"
        - "!node_modules/**"
        - "!package**"
    events:
      - httpApi:
          method: get
          path: /
          authorizer:
            name: customAuthorizer

  login:
    handler: handlers/login.handler
    package:
      patterns:
        - "!handlers/**"
        - "handlers/login.js"
    events:
      - httpApi:
          method: post
          path: /

  authorizerFunc:
    handler: handlers/auth.handler
    package:
      patterns:
        - "!handlers/**"
        - "handlers/auth.js"

plugins:
  - serverless-ignore
  - serverless-dotenv-plugin